agent_name: rysk_roller
author: eightballer
version: 0.1.0
license: Apache-2.0
description: The rysk roller is a trading agent designed to run on the Rysk network.
aea_version: '>=1.32.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeigtjiag4a2h6msnlojahtc5pae7jrphjegjb3mlk2l54igc4jwnxe
- valory/http_client:0.23.0:bafybeifmdc5nag3ca2vv5oc4yb3pioxsbykjesxeeecdhv4nrg6ecfcuey
- valory/ipfs:0.1.0:bafybeih7xqo3w327wrqaydkwt4bbm3jsnepvkaypwh4j4gtbgpvfon7xfa
- valory/ledger:0.19.0:bafybeig6jdopgedy5wohwtm3zsqgchcq3sbnb4x4p3vxbwlgikhui65pre
- valory/p2p_libp2p_client:0.1.0:bafybeidykjqleqy343puirang57xjjiuqpfiu2mlhpbwedmxvvfw3r3774
contracts:
- valory/service_registry:0.1.0:bafybeibt3uhw7s72subuiqve2jd3mrd4vot7fh3jsdjd5d35wuiicaemv4
- valory/uniswap_v2_erc20:0.1.0:bafybeifewyykjldtaaece4xhguveuj54zqrhf3cw35i6zhjaaubjluerj4
- zarathustra/homm_vault:0.1.0:bafybeid5fwit4ypxaqvknrefmfe6vq3psdzfue6oc2oqftfzcw3islvjnq
protocols:
- open_aea/signing:1.0.0:bafybeiaiih7qno6ctkwyvmkx2m2i4vzvhwx5zbnu7c2siqx7vresuep6qm
- valory/abci:0.1.0:bafybeih3jhbahoqi26tcqjommne2xxaxjslirbnidhhx5tit4gkvfuxaom
- valory/acn:1.1.0:bafybeiau7lc4ey6af24jg2e2rrmrhvpqkhyaxofgr2on27htealrhptoiy
- valory/contract_api:1.0.0:bafybeibcmlxllyrfbp244upa2ea7hhliawv64ldrrn3fb64fdx2342orsy
- valory/http:1.0.0:bafybeibgndpi4ltohlanqkywz6zwcsfjho3ypjtoyu4h3fvkk4sk5yllku
- valory/ipfs:0.1.0:bafybeihcqvmnyochqkkl3u7rqiewkth4onabllac72veunmddeem2ykfia
- valory/ledger_api:1.0.0:bafybeieoq3vtqst3hrbhxqchqkqd3hhbcf6rwgkz7zhnbupa6ecpgeesdi
- valory/tendermint:0.1.0:bafybeicavolm7gshxgdsiokj2hnhrm2m4j4ljrvm6nvvupmszp7da56gxm
skills:
- eightballer/rysk_roller:0.1.0:bafybeigldjkkdkgh7gw5m5fs73jvf7ruquxts5idfzpqkrkmuntpkgopxe
- valory/abstract_abci:0.1.0:bafybeia7z7grrixjkofv7z3o7wyxodquiqrlqpnhzlpbwbolcau5ht6gz4
- valory/abstract_round_abci:0.1.0:bafybeibj5lhxkmfy33a2llmjyma52al26iijdq4epl3h2yljgrjejqswxe
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  handlers:
    console:
      class: rich.logging.RichHandler
      level: DEBUG
  loggers:
    aea:
      handlers:
      - console
      level: INFO
      propagate: false
dependencies:
  open-aea-ledger-ethereum-hwi: {}
  rich: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: eightballer/rysk_roller:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
is_abstract: false
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:https://arbitrum-goerli.rpc.thirdweb.com}
      chain_id: ${int:421613}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: eightballer/rysk_roller:0.1.0
type: skill
models:
  params:
    args:
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      use_termination: ${bool:false}
      vault_address: ${str:0x0000000000000000000000000000000000000000}
