agent_name: rysk_roller
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.32.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeigr7khpdtaad4okzu2f3zfvdxsluzewfr2tszvapmj3gyy7clabeu
- valory/http_client:0.23.0:bafybeicxuedaogf2q4z3zekgr2yvsxt6tieo3fzv7deg3734datprtsyry
- valory/ipfs:0.1.0:bafybeifo4tzgjtkt422ks3ooipum7p4ycr6rrdtuab246owo2r74vmseee
- valory/ledger:0.19.0:bafybeiehwka634iicodmzolflo2le6pdlfmb4dgtnhszjcccoanyay75gm
- valory/p2p_libp2p_client:0.1.0:bafybeidfm65eece533hfvg2xyn4icpmvz4lmvbemstrlo3iuffb7e72ycq
contracts:
- valory/service_registry:0.1.0:bafybeibt3uhw7s72subuiqve2jd3mrd4vot7fh3jsdjd5d35wuiicaemv4
- valory/uniswap_v2_erc20:0.1.0:bafybeieh4h5pedo3otnxq4h43fyg6f6t7bbn7vncqv2hhj5z5wvwo72bsm
- valory/uniswap_v2_router_02:0.1.0:bafybeie6dabrmod674i2nvotde2rodjlslh5ngxmm5pd7u632oi32tf6om
- zarathustra/homm_vault:0.1.0:bafybeigkietdimlhzwnjdifdthy6uzna36zdj5cthqhh5q5erfddtucnpm
protocols:
- open_aea/signing:1.0.0:bafybeigqmouus33blg3ttpbtmy2tbhzyaefeyumxhfzxobpw43mocf7sru
- valory/abci:0.1.0:bafybeifsttranjnxstpoyswpm2dzfyzimpatdfbu5pdpu7ibmda5x24ipe
- valory/acn:1.1.0:bafybeif2th25e4gaejgpg373wal4bkpyfxdbee7f7gbrb64vrgrwhbakxm
- valory/contract_api:1.0.0:bafybeihzhpxgwxkapv73bc5mytc77u557e7upmmahgoyqndysjkzvxxcyy
- valory/http:1.0.0:bafybeieshrrplt5oadws5tz3rhjo6m2spchdyhkwa2z6ze2bs4ivauusfq
- valory/ipfs:0.1.0:bafybeidjn5fa2tjah3jif4tt67rccvtflkmkj5gnjq2jssdkxdzwrzzasy
- valory/ledger_api:1.0.0:bafybeiachflkr2syxjzele5ie7tioozyfqpb3u4r2h7vs66jiqrzhineyy
- valory/tendermint:0.1.0:bafybeib25ulpp3tri3ppexk4t6yttuajhr7wpgs7wajpsnbbnzo256ubem
skills:
- eightballer/rysk_roller:0.1.0:bafybeiazd5f56gdlx6co4bhxy25nm4cpzpnhjf4zsx4uzh6ew2ejw3onhi
- valory/abstract_abci:0.1.0:bafybeihlgivyusw3d4unhupidkvtalllqfvukbkk5r7hztjzy5qm4gpxei
- valory/abstract_round_abci:0.1.0:bafybeief2qtrja6n5p44lkh6ivoq5ias6thnut6xozwdk5ahdpt4rvjuei
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  handlers:
    console:
      class: rich.logging.RichHandler
      level: DEBUG
  loggers:
    aea:
      handlers:
      - console
      level: INFO
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: eightballer/rysk_roller:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
is_abstract: false
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://arbitrum-goerli.rpc.thirdweb.com
      chain_id: 421613
      poa_chain: false
      default_gas_price_strategy: eip1559
---
public_id: eightballer/rysk_roller:0.1.0
type: skill
models:
  params:
    args:
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      use_termination: ${bool:false}
      vault_address: ${str:0x0000000000000000000000000000000000000000}
