name: rysk_roller
author: eightballer
version: 0.1.0
description: A Proof of concept for a Options trading Multi Agent Service.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: eightballer/rysk_roller:0.1.0:bafybeifmcek7r55fgyps7gu24dm3liqzpmzjwi2oer2kzqvlgcfc4sdrdu
number_of_agents: 4
deployment:
  agent:
    ports:
      0:
        8000: 8000
      1:
        8001: 8000
      2:
        8002: 8000
      3:
        8003: 8000
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${ETHEREUM_ADDRESS:str:https://arbitrum-goerli.rpc.thirdweb.com}
      chain_id: ${ETHEREUM_CHAIN_ID:int:421613}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: eightballer/rysk_roller:0.1.0:bafybeicmuthcay6doky6sgy235n52chsk5fkzswpvyg5s4yeptvmzmxoqy
type: skill
models:
  params:
    args:
      setup:
        consensus_threshold: 1
        safe_contract_address: '0x0000000000000000000000000000000000000000'
        all_participants:
        - ${MAS_ADDRESS:str}
      tendermint_p2p_url: node0:26656
      tendermint_com_url: http://node0:8080
